/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Registro;
import Modelo.Bodega;
import Modelo.Producto;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author administrador
 */
public class Jfm_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Jfm_Producto
     */
    public Jfm_Producto() {
        initComponents();
        
        //Llenar el combobox con las bodegas creadas en la bbdd
        //para que se muestre bien en pantalla es necesario cambiarle el toString a Bodega
        //para que muestre solo el nombre
        Registro rg = new Registro();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jcb_bodega.getModel();
        modelo.removeAllElements();
        List<Bodega> lista = rg.buscarTodosBodega();
        
        for (Bodega bodega : lista) {
            modelo.addElement(bodega);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_nombre_producto = new javax.swing.JTextField();
        jtxt_marca = new javax.swing.JTextField();
        jtxt_modelo = new javax.swing.JTextField();
        jtxt_id_producto = new javax.swing.JTextField();
        jtxt_stock = new javax.swing.JTextField();
        jbtm_guardar_producto = new javax.swing.JButton();
        jbtm_ingresar_otro_producto = new javax.swing.JButton();
        jbtm_salir_menu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcb_bodega = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ingresar Producto");

        jLabel2.setText("Nombre");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("ID Producto");

        jLabel6.setText("Stock");

        jtxt_id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_id_productoActionPerformed(evt);
            }
        });

        jbtm_guardar_producto.setText("Guardar Producto");
        jbtm_guardar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtm_guardar_productoActionPerformed(evt);
            }
        });

        jbtm_ingresar_otro_producto.setText("Ingresar otro Producto");
        jbtm_ingresar_otro_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtm_ingresar_otro_productoActionPerformed(evt);
            }
        });

        jbtm_salir_menu.setText("Salir al Menú");
        jbtm_salir_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtm_salir_menuActionPerformed(evt);
            }
        });

        jLabel7.setText("Bodega asociada");

        jcb_bodega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_bodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_bodegaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxt_nombre_producto)
                                    .addComponent(jtxt_marca)
                                    .addComponent(jtxt_modelo)
                                    .addComponent(jtxt_id_producto)
                                    .addComponent(jtxt_stock)
                                    .addComponent(jcb_bodega, 0, 162, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jbtm_guardar_producto)
                                .addGap(18, 18, 18)
                                .addComponent(jbtm_ingresar_otro_producto))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jbtm_salir_menu)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcb_bodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtm_guardar_producto)
                    .addComponent(jbtm_ingresar_otro_producto))
                .addGap(18, 18, 18)
                .addComponent(jbtm_salir_menu)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtm_guardar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtm_guardar_productoActionPerformed
        //        capturar datos
        String nombre,marca,modelo;
        int idProducto,stock;
        Bodega bodega = new Bodega();
        
        nombre = this.jtxt_nombre_producto.getText();
        marca = this.jtxt_marca.getText();
        modelo = this.jtxt_modelo.getText();
        idProducto = Integer.valueOf(this.jtxt_id_producto.getText());
        stock = Integer.valueOf(this.jtxt_stock.getText());
        
        //esta línea captura la bodega seleccionada
        bodega = (Bodega)this.jcb_bodega.getSelectedItem();        

        Producto producto = new Producto(nombre, marca, modelo, idProducto, stock, bodega);
        
        Registro reg = new Registro();
        reg.agregarProducto(producto);
        JOptionPane.showMessageDialog(this, "Registro exitoso de "+nombre);

    }//GEN-LAST:event_jbtm_guardar_productoActionPerformed

    private void jbtm_ingresar_otro_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtm_ingresar_otro_productoActionPerformed
       this.jtxt_nombre_producto.setText("");
       this.jtxt_marca.setText("");
       this.jtxt_modelo.setText("");
       this.jtxt_stock.setText("");
       this.jtxt_id_producto.setText("");
    }//GEN-LAST:event_jbtm_ingresar_otro_productoActionPerformed

    private void jcb_bodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_bodegaActionPerformed

    }//GEN-LAST:event_jcb_bodegaActionPerformed

    private void jtxt_id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_id_productoActionPerformed

    private void jbtm_salir_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtm_salir_menuActionPerformed
       dispose();
    }//GEN-LAST:event_jbtm_salir_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfm_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfm_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfm_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfm_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfm_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtm_guardar_producto;
    private javax.swing.JButton jbtm_ingresar_otro_producto;
    private javax.swing.JButton jbtm_salir_menu;
    private javax.swing.JComboBox<String> jcb_bodega;
    private javax.swing.JTextField jtxt_id_producto;
    private javax.swing.JTextField jtxt_marca;
    private javax.swing.JTextField jtxt_modelo;
    private javax.swing.JTextField jtxt_nombre_producto;
    private javax.swing.JTextField jtxt_stock;
    // End of variables declaration//GEN-END:variables
}
